Sprint 2
SDS90/middle.messenger.praktikum.yandex pull request #3
Opened 2022-05-06 22:05 UTC by SDS90

Реализован собственный генератор шаблонов TemplateGen. На его базе пересобран весь проект с учётом разделения структуры по элементам.

Реализован базовый класс Block.

Реализован HTTPTransport для работы с запросами.

Добавлена валидация на формы авторизации, регистрации, изменения профиля. Форма отправки сообщения не будет отправлена без текста сообщения или прикреплённого файла.

2022-05-07 06:19 UTC, agadoev requested changes
Привет
Спасибо за работу
Я отметил некоторые места, на которые стоит обратить внимание. Поправь их и двинемся дальше :)

2022-05-07 06:19 UTC, agadoev commented on package.json
> +    "eslint": "eslint"
Тут стоит указать путь к папке, которую надо линтить, иначе линтер запустится и сразу завершится

eslint ./src

2022-05-07 06:19 UTC, agadoev commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^5.22.0",
Версии библиотек лучше делать фиксированными, чтобы лучше контролировать зависимости и быть уверенным, что однажды какой-то из пакетов не упадет с ошибкой при билде
Например: вместо "^5.22.0" писать "5.22.0"

Полезная статья на эту тему https://semver.org/lang/ru/

2022-05-07 06:19 UTC, agadoev commented on src/elements/add-file-block.ts
> +			inner.querySelector('input').addEventListener('change', this.props.onChange);
querySelector может вернуть null и тогда вылетить ошибка
Лучше вызвать селектор, а затем вручную проверить inner на null, а уже потом вешать listener

2022-05-07 06:19 UTC, agadoev commented on src/elements/input-block.ts
> +			const input = inner.querySelector('input');
нужно добавить проверку input на null

2022-05-07 06:19 UTC, agadoev commented on src/elements/input-block.ts
> +				input.classList.add('focus-input');
внутри функции input можно заменить на this. Так будет чище

2022-05-07 06:19 UTC, agadoev commented on src/elements/textarea-block.ts
> +
Нужно добавить проверку на null

2022-05-07 06:19 UTC, agadoev commented on src/elements/textarea-block.ts
> +				textarea.classList.add('focus-input');
Можно заменить textarea на this

2022-05-07 06:19 UTC, agadoev commented on src/elements/textarea-block.ts
> +	insertBlock(element: string, clean: boolean): Record<string, HTMLElement> {
методы insertBlock в этом компоненте и в textarea-block дублируются, может стоит вынести эту функцию как отдельную, принимающую компонент как аргумент?

2022-05-07 06:19 UTC, agadoev commented on src/elements/button-block.ts
> +	insertBlock(element: string, clean: boolean): Record<string, HTMLElement> {
Во всех компонентах дублируется этот метод
Может стоит его вынести в родительский компонент Block?

2022-05-07 12:36 UTC, SDS90 commented on src/elements/button-block.ts
> +	insertBlock(element: string, clean: boolean): Record<string, HTMLElement> {
Проблема была в том, что в некоторых элементах в insertBlock  дополнительно вешаются события:

`inner.addEventListener('click', this.props.onClick);` в button-blocks.
focus и blur на элементы формы в textarea и input.

Думал, что события не будут корректно работать, если их вешать после добавления блока на страницу. Перенёс в родительский компонент, работает.

2022-05-07 14:20 UTC, SDS90 commented on src/elements/button-block.ts
> +	insertBlock(element: string, clean: boolean): Record<string, HTMLElement> {
Подскажи, пожалуйста, с чем может быть связана такая ошибка на гитхабе:

![image](https://user-images.githubusercontent.com/5861842/167258257-5e9a2f3c-a076-4802-b463-a739da5fd836.png)

Появилась после исправления замечаний.

При этом на netlify всё деплоится без проблем:
![image](https://user-images.githubusercontent.com/5861842/167258277-05ab5d08-8242-4707-a0f2-5e2f9ffb53aa.png)

У себя со сборкой тоже проблем не вижу.

2022-05-11 18:13 UTC, agadoev commented
Привет
Спасибо за правки, работу принимаю)
Удачи в дальнейшем

P.S. Ссылка в README почему-то указывала на первый PR

2022-05-22 11:32 UTC, merged