Sprint 3
SDS90/middle.messenger.praktikum.yandex pull request #4
Opened 2022-06-05 20:00 UTC by SDS90

2022-06-06 13:48 UTC, podlovchenko requested changes
Привет, по работе системы все хорошо 👍 
Есть несколько замечаний:
1. Есть ошибки при сборке
2. Много закомментированного кода
3. Не забывай обновлять netlify)

2022-06-06 13:48 UTC, podlovchenko commented on src/api/apiChats.ts
> +			withCredentials: true,
Если используется в каждом запросе, то стоит указать параметром по умолчанию в HTTPTransport

2022-06-06 13:48 UTC, podlovchenko commented on src/api/apiUser.ts
> +			headers: {},
Зачем?

2022-06-06 13:48 UTC, podlovchenko commented on src/controllers/authentificationController2.ts
> +			//afterAuthorizationAnswer(answer, callback, '/messenger');
Закомментированный код лучше не оставлять

2022-06-06 13:48 UTC, podlovchenko commented on src/pages/profile.ts
> +			window.history.back();
Есть же класс Router

2022-06-06 19:36 UTC, SDS90 commented on src/api/apiChats.ts
> +			withCredentials: true,
fixed

2022-06-06 19:36 UTC, SDS90 commented on src/api/apiUser.ts
> +			headers: {},
fixed

2022-06-06 19:36 UTC, SDS90 commented on src/controllers/authentificationController2.ts
> +			//afterAuthorizationAnswer(answer, callback, '/messenger');
fixed

2022-06-06 19:36 UTC, SDS90 commented on src/pages/profile.ts
> +			window.history.back();
fixed

2022-06-07 09:51 UTC, podlovchenko commented
Работу принимаю, чтобы убрать ошибки сборки нужно удалить файл babel.config.js, он не нужен

2022-06-07 09:51 UTC, podlovchenko approved these changes

2022-06-14 17:27 UTC, merged